import * as images from "./ImagesImports";
enum ProjectType {
  FrontEnd = "FrontEnd",
  Backend = "Backend",
  FullStack = "FullStack",
}

export const projectsData = [
  {
    id: 0,
    image: images.NaturalFrontImg,
    title: "Natural Tours ",
    desc: "The Front End part of Booking Tours online project.",
    type: ProjectType.FrontEnd,
    tools: [
      "ReactJs",
      "Redux",
      "Saga",
      "SCSS",
      "Axios",
      "Formik",
      "Yup",
      "Ant Design",
      "I18next",
      "MapBox",
      "Stripe",
      "OAuth",
      "PassportJs",
      "chart.js",
      "Eslint",
    ],
    icons: [
      images.reactImg,
      images.reduxImg,
      images.reduxsagaImg,
      images.sassImg,
      images.axiosImg,
      images.formikImg,
      images.noLogoImg,
      images.antImg,
      images.i18nextImg,
      images.mapboxImg,
      images.stripeImg,
      images.oauthImg,
      images.passportImg,
      images.chartImg,
      images.eslintImg,
    ],
    images: [
      images.NtoursImg1,
      images.Ntour1,
      images.Ntour2,
      images.Ntour3,
      images.Ntour4,
      images.Ntour5,
      images.Ntour6,
      images.Ntour7,
      images.Ntour7,
      images.Ntour9,
      images.Ntour10,
      images.Ntour11,
      images.Ntour12,
      images.Ntour13,
      images.Ntour14,
    ],
    features: [
      "CRUD on tours, users, bookings, reviews",
      "Authentication using Jwt web tokens and refresh tokens.",
      "Change password and reset password using email.",
      "Uploading images and processing them.",
      "Credit Card Payments with Stripe.",
      "Login with facebook and gmail.",
    ],
    youtube: "https://www.youtube.com/embed/4VrSu75fmSE",
    demo: "https://natural-tours.netlify.app/",
    source: "https://github.com/muhannad35990/NatureTours-React.JS",
  },
  {
    id: 1,
    image: images.NaturalBackImg,
    title: "Natural Tours ",
    desc: "The Back End part of Booking Tours online project.",
    type: ProjectType.Backend,
    tools: [
      "NodeJs",
      "Express",
      "MongoDB",
      "REST",
      "JWT",
      "Stripe",
      "Oauth",
      "PassportJs",
      "heroku",
      "Webhooks",
      "Eslint",
    ],
    icons: [
      images.nodeImg,
      images.expressImg,
      images.mongoImg,
      images.restImg,
      images.jwtImg,
      images.stripeImg,
      images.oauthImg,
      images.passportImg,
      images.herokuImg,
      images.webhooksImg,
      images.eslintImg,
    ],
    images: [images.NtoursImg1],
    features: [
      "CRUD on tours, users, bookings, reviews",
      "Authentication using Jwt web tokens and refresh tokens",
      "Change password and reset password using email",
      "Uploading images and processing them",
      "Credit Card Payments with Stripe",
      "Login with facebook and gmail",
      "Preventing Parameter Pollution in monogodb",
      "Data sanitization against NOSQL query injection and XSS",
      "Limiting number of requests to the backend from IP address by time to protect against DOS attack",
      "Compress all text sent to the client",
    ],
    source: "https://github.com/muhannad35990/NatureToursAPI",
  },
  {
    id: 2,
    image: images.realEstateImg,
    title: "Real estate site",
    desc: "This is a landing page for real-estate and realtors.",
    type: ProjectType.FrontEnd,
    tools: ["ReactJs", "JAVASCRIPT", "MUI", "SCSS"],
    icons: [
      images.reactImg,
      images.javascriptImg,
      images.materialuiImg,
      images.sassImg,
    ],
    images: [
      images.Rstate1,
      images.Rstate2,
      images.Rstate3,
      images.Rstate4,
      images.Rstate5,
      images.Rstate6,
    ],
    features: [
      "Landing page for real-estate and realtors",
      "Different section for different features",
      "Cool animation",
      "responsive design",
    ],
    source: "https://github.com/muhannad35990/real-estate ",
    demo: "https://competent-knuth-1aab9a.netlify.app/",
  },
  {
    id: 3,
    image: images.touristsImg,
    title: "Tourists site",
    desc: "This is a landing page for tours and Tourists. ",
    type: ProjectType.FrontEnd,
    tools: ["ReactJs", "JAVASCRIPT", "MUI", "SCSS"],
    icons: [
      images.reactImg,
      images.javascriptImg,
      images.materialuiImg,
      images.sassImg,
    ],
    images: [
      images.Toursit1,
      images.Toursit2,
      images.Toursit3,
      images.Toursit4,
      images.Toursit5,
      images.Toursit6,
      images.Toursit7,
      images.Toursit8,
    ],
    features: [
      "Landing page for Tourists site",
      "Different section for different features",
      "Cool animation",
      "responsive design",
    ],
    source: "https://github.com/muhannad35990/TouristSite",
    demo: "https://silly-jones-4fbb74.netlify.app/",
  },
  {
    id: 4,
    image: images.hotelsImg,
    title: "Hotels booking",
    desc: "This is a landing page for hotels booking.",
    type: ProjectType.FrontEnd,
    tools: ["ReactJs", "JAVASCRIPT", "MUI", "SCSS"],
    icons: [
      images.reactImg,
      images.javascriptImg,
      images.materialuiImg,
      images.sassImg,
    ],
    images: [images.Hotel1, images.Hotel2, images.Hotel3],
    features: [
      "Landing page for Hotel site",
      "Different section for different features",
      "Cool animation",
      "responsive design",
    ],
    source: "https://github.com/muhannad35990/hotelsBook",
    demo: "https://gallant-heisenberg-00eac7.netlify.app/",
  },
  {
    id: 5,
    image: images.whatsappImg,
    title: "Whatsapp web clone",
    desc: "This is a Clone of whatsapp web application. ",
    type: ProjectType.FullStack,
    tools: ["ReactJs", "Firebase", "MUI", "CSS"],
    icons: [
      images.reactImg,
      images.firebaseImg,
      images.materialuiImg,
      images.cssimg,
    ],
    images: [images.Whatsapp1, images.Whatsapp2],
    features: [
      "Fully working whatsapp web clone",
      "Group chat messaging",
      "Firebase for the Backend",
      "Login with gmail",
    ],
    source: "https://github.com/muhannad35990/whatsapp-webClone",
    demo: "https://whatsappweb-clone-6b5b8.web.app/",
  },
  {
    id: 6,
    image: images.videochatImg,
    title: "Video audio chat",
    desc: "This is a video audioweb chat application.",
    type: ProjectType.FullStack,
    tools: ["NodeJs", "Express", "socket.io", "CSS"],
    icons: [images.nodeImg, images.expressImg, images.socketImg, images.cssimg],
    images: [images.videochatImg],
    features: [
      "CRUD on tours, users, bookings, reviews",
      "Authentication using Jwt web tokens and refresh tokens.",
      "Change password and reset password using email.",
      "Uploading images and processing them.",
      "Credit Card Payments with Stripe.",
      "Login with facebook and gmail.",
    ],
    source: "https://github.com/muhannad35990/video-audio-chat-nodejs",
    demo: "https://meeting-video-chat.herokuapp.com/",
  },
  {
    id: 7,
    image: images.chatImg,
    title: "chat Application",
    desc: "This is a full stack local messenger using local storage.",
    type: ProjectType.FullStack,
    tools: ["ReactJs", "NodeJs", "socket.io", "Bootstrap"],
    icons: [
      images.reactImg,
      images.nodeImg,
      images.socketImg,
      images.bootstrapImg,
    ],
    images: [
      images.NtoursImg1,
      images.NtoursImg1,
      images.NtoursImg1,
      images.NtoursImg1,
    ],
    features: [
      "CRUD on tours, users, bookings, reviews",
      "Authentication using Jwt web tokens and refresh tokens.",
      "Change password and reset password using email.",
      "Uploading images and processing them.",
      "Credit Card Payments with Stripe.",
      "Login with facebook and gmail.",
    ],
    source: "https://github.com/muhannad35990/Messenger_FullStack",
  },
  {
    id: 8,
    image: images.muhannadImg,
    title: "Muhannad portfolio",
    desc: "This project of my protfolio",
    type: ProjectType.FrontEnd,
    tools: ["ReactJs", "Styled-components", "Typescript", "MUI"],
    icons: [
      images.reactImg,
      images.styledComponentsImg,
      images.typescriptImg,
      images.materialuiImg,
    ],
    images: [
      images.NtoursImg1,
      images.NtoursImg1,
      images.NtoursImg1,
      images.NtoursImg1,
    ],
    features: [
      "CRUD on tours, users, bookings, reviews",
      "Authentication using Jwt web tokens and refresh tokens",
      "Change password and reset password using email",
      "Uploading images and processing them",
      "Credit Card Payments with Stripe",
      "Login with facebook and gmail",
    ],
    source: "https://github.com/muhannad35990/muhannad-portfolio",
  },
];
