import * as images from "./ImagesImports";

export const skillsData = [
  { name: "HTML5", rate: 99, img: images.htmlimg },
  { name: "CSS3", rate: 99, img: images.cssimg },
  { name: "SASS", rate: 99, img: images.sassImg },
  { name: "Bootstrap", rate: 95, img: images.bootstrapImg },
  { name: "Tailwind", rate: 95, img: images.tailwindImg },
  { name: "Material-ui", rate: 99, img: images.materialuiImg },
  { name: "Ant design", rate: 99, img: images.antImg },

  { name: "JAVASCRIPT", rate: 99, img: images.javascriptImg },
  { name: "TypeScript", rate: 99, img: images.typescriptImg },
  { name: "React.js", rate: 99, img: images.reactImg },
  { name: "Redux", rate: 99, img: images.reduxImg },
  { name: "redux-saga", rate: 99, img: images.reduxsagaImg },
  { name: "Styled components", rate: 99, img: images.styledComponentsImg },
  { name: "Formik", rate: 99, img: images.formikImg },
  { name: "Yup", rate: 99, img: images.noLogoImg },
  { name: "Node.js", rate: 90, img: images.nodeImg },
  { name: "REST", rate: 99, img: images.restImg },
  { name: "MongoDB", rate: 95, img: images.mongoImg },
  { name: "SQL", rate: 90, img: images.sqlImg },
  { name: "Git,GitHub", rate: 99, img: images.gitImg },
  { name: "Agile, JIRA", rate: 99, img: images.jiraImg },
  { name: "Firebase", rate: 70, img: images.firebaseImg },
  { name: "Docker", rate: 70, img: images.dockerImg },
  { name: "Oauth", rate: 90, img: images.oauthImg },
  { name: "Stripe", rate: 95, img: images.stripeImg },
  { name: "PassportJs", rate: 95, img: images.passportImg },
  { name: "I18next", rate: 99, img: images.i18nextImg },
  { name: "Mapbox", rate: 95, img: images.mapboxImg },
  { name: "Chart.js", rate: 90, img: images.chartImg },
  { name: "Socket.io", rate: 90, img: images.socketImg },
  { name: "Axios", rate: 99, img: images.axiosImg },
  { name: "Eslint", rate: 99, img: images.eslintImg },
];
